force-app/main/default/objects/Account/fields/ceoName__c.field-meta.xml
<CustomField>
    <fullName>ceoName__c</fullName>
    <label>ceoName</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountDetail__c/AccountDetail__c.object-meta.xml
<CustomObject>
    <label>AccountDetail</label>
    <nameField>
        <label>AccountDetail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AccountDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountDetail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>AccountDetails</relationshipLabel>
    <relationshipName>AccountDetails</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/AccountDetail__c/fields/ceoName__c.field-meta.xml
<CustomField>
    <fullName>ceoName__c</fullName>
    <label>ceoName</label>
    <length>234</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AccountDetail__c/fields/LastYearRevenue__c.field-meta.xml
<CustomField>
    <fullName>LastYearRevenue__c</fullName>
    <label>LastYearRevenue</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/CustomerProfileController.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 10-18-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class CustomerProfileController {
    @AuraEnabled

    public static ComponentResponse initialize(String recordId){

        ComponentResponse response = new ComponentResponse();

        try {

            //AccountDetail RecordId를 이용하여 Account(Master-Detail)Id를 조회 후,

            //Account Record 조회 및 ComponentResponse리턴

            AccountDetail__c accDetail = [

                SELECT

                    Id,

                    Name,

                    Account__c,

                    LastYearRevenue__c,

                    Account__r.Name,

                    Account__r.Phone,

                    Account__r.ceoName__c   //custome field는 무조건 __c 를 붙여야한다!

                FROM AccountDetail__c

                WHERE Id = :recordId

            ];



            response.setData('accountDetail', accDetail);



        } catch (Exception e) {

            throw new AuraHandledException(e.getMessage());

        }

        return response;

    }
}